# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def computeRiccicurvature3D(Riccitensor=None,reciprocalmetriccoefficients=None,*args,**kwargs):
    varargin = computeRiccicurvature3D.varargin
    nargin = computeRiccicurvature3D.nargin

    ##
#        Project: Fluid - structure interaction on deformable surfaces
#         Author: Luca Di Stasio
#    Institution: ETH Zrich
#                 Institute for Building Materials
# Research group: Computational Physics for Engineering Materials
#        Version: 0.1
#  Creation date: May 29th, 2014
#    Last update: May 29th, 2014
    
    #    Description: 
#          Input: 
#         Output:
    
    ##
    
    G11=reciprocalmetriccoefficients[:,1]
    G22=reciprocalmetriccoefficients[:,2]
    G33=reciprocalmetriccoefficients[:,3]
    G12=reciprocalmetriccoefficients[:,4]
    G13=reciprocalmetriccoefficients[:,5]
    G23=reciprocalmetriccoefficients[:,6]
    R11=Riccitensor[:,1]
    R22=Riccitensor[:,2]
    R33=Riccitensor[:,3]
    R12=Riccitensor[:,4]
    R13=Riccitensor[:,5]
    R23=Riccitensor[:,6]
    R=multiply(G11,R11) + multiply(G22,R22) + multiply(G33,R33) + multiply(G12,R12) + multiply(G13,R13) + multiply(G23,R23)
    return R