# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def computecontravariantvectorcomponents3D(contravariantbase=None,*args,**kwargs):
    varargin = computecontravariantvectorcomponents3D.varargin
    nargin = computecontravariantvectorcomponents3D.nargin

    ##
#        Project: Fluid - structure interaction on deformable surfaces
#         Author: Luca Di Stasio
#    Institution: ETH Zrich
#                 Institute for Building Materials
# Research group: Computational Physics for Engineering Materials
#        Version: 0.1
#  Creation date: May 28th, 2014
#    Last update: May 30th, 2014
    
    #    Description: 
#          Input: 
#         Output:
    
    ##
    
    G1=contravariantbase[:,1:3]
    G2=contravariantbase[:,4:6]
    G3=contravariantbase[:,7:9]
    v1=sum(multiply(v,G1),2)
    v2=sum(multiply(v,G2),2)
    v3=sum(multiply(v,G3),2)
    vI=matlabarray(cat(v1,v2,v3))
    return vI