# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def computemetriccoefficients3Dsurface(covariantbase=None,*args,**kwargs):
    varargin = computemetriccoefficients3Dsurface.varargin
    nargin = computemetriccoefficients3Dsurface.nargin

    ##
#        Project: Fluid - structure interaction on deformable surfaces
#         Author: Luca Di Stasio
#    Institution: ETH Zrich
#                 Institute for Building Materials
# Research group: Computational Physics for Engineering Materials
#        Version: 0.1
#  Creation date: July 17th, 2014
#    Last update: July 17th, 2014
    
    #    Description: 
#          Input: 
#         Output:
    
    ##
    
    g11=sum(multiply(covariantbase[:,1:3],covariantbase[:,1:3]),2)
    g22=sum(multiply(covariantbase[:,4:6],covariantbase[:,4:6]),2)
    g12=sum(multiply(covariantbase[:,1:3],covariantbase[:,4:6]),2)
    g=multiply(g11,g22) - multiply(g12,g12)
    sqrtg=sqrt(g)
    metriccoefficients=matlabarray(cat(g11,g22,g12))
    return metriccoefficients,g,sqrtg