# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def computereciprocalmetriccoefficients3Dsurface(contravariantbase=None,*args,**kwargs):
    varargin = computereciprocalmetriccoefficients3Dsurface.varargin
    nargin = computereciprocalmetriccoefficients3Dsurface.nargin

    ##
#        Project: Fluid - structure interaction on deformable surfaces
#         Author: Luca Di Stasio
#    Institution: ETH Zrich
#                 Institute for Building Materials
# Research group: Computational Physics for Engineering Materials
#        Version: 0.1
#  Creation date: July 17th, 2014
#    Last update: July 17th, 2014
    
    #    Description: 
#          Input: 
#         Output:
    
    ##
    
    g11=sum(multiply(contravariantbase[:,1:3],contravariantbase[:,1:3]),2)
    g22=sum(multiply(contravariantbase[:,4:6],contravariantbase[:,4:6]),2)
    g12=sum(multiply(contravariantbase[:,1:3],contravariantbase[:,4:6]),2)
    g=multiply(g11,g22) - multiply(g12,g12)
    sqrtg=sqrt(g)
    reciprocalmetriccoefficients=matlabarray(cat(g11,g22,g12))
    return reciprocalmetriccoefficients,g,sqrtg