# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def computeRiemanntensor3Dsurface(N=None,deltaq=None,secondChristoffelsymbol=None,metriccoefficients=None,firstdevneighbours=None,*args,**kwargs):
    varargin = computeRiemanntensor3Dsurface.varargin
    nargin = computeRiemanntensor3Dsurface.nargin

    ##
#        Project: Fluid - structure interaction on deformable surfaces
#         Author: Luca Di Stasio
#    Institution: ETH Zrich
#                 Institute for Building Materials
# Research group: Computational Physics for Engineering Materials
#        Version: 0.1
#  Creation date: July 18th, 2014
#    Last update: July 18th, 2014
    
    #    Description: 
#          Input: 
#         Output:
    
    ##
    
    g11=metriccoefficients[:,1]
    g22=metriccoefficients[:,2]
    g12=metriccoefficients[:,3]
    Gamma111=secondChristoffelsymbol[:,1]
    Gamma112=secondChristoffelsymbol[:,2]
    Gamma121=secondChristoffelsymbol[:,3]
    Gamma122=secondChristoffelsymbol[:,4]
    Gamma211=secondChristoffelsymbol[:,5]
    Gamma212=secondChristoffelsymbol[:,6]
    Gamma221=secondChristoffelsymbol[:,7]
    Gamma222=secondChristoffelsymbol[:,8]
    Gamma111d1=zeros(N,1)
    Gamma112d1=zeros(N,1)
    Gamma121d1=zeros(N,1)
    Gamma122d1=zeros(N,1)
    Gamma211d1=zeros(N,1)
    Gamma212d1=zeros(N,1)
    Gamma221d1=zeros(N,1)
    Gamma222d1=zeros(N,1)
    Gamma111d2=zeros(N,1)
    Gamma112d2=zeros(N,1)
    Gamma121d2=zeros(N,1)
    Gamma122d2=zeros(N,1)
    Gamma211d2=zeros(N,1)
    Gamma212d2=zeros(N,1)
    Gamma221d2=zeros(N,1)
    Gamma222d2=zeros(N,1)
    for i in arange(1,N).reshape(-1):
        j1=1
        if 1 == firstdevneighbours[i,dot(4,(j1 - 1)) + 1]:
            Gamma111d1[i,1]=multiply(0.5,(Gamma111[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1] - Gamma111[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1])) / deltaq[j1]
            Gamma112d1[i,1]=multiply(0.5,(Gamma112[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1] - Gamma112[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1])) / deltaq[j1]
            Gamma121d1[i,1]=multiply(0.5,(Gamma121[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1] - Gamma121[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1])) / deltaq[j1]
            Gamma122d1[i,1]=multiply(0.5,(Gamma122[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1] - Gamma122[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1])) / deltaq[j1]
            Gamma211d1[i,1]=multiply(0.5,(Gamma211[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1] - Gamma211[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1])) / deltaq[j1]
            Gamma212d1[i,1]=multiply(0.5,(Gamma212[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1] - Gamma212[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1])) / deltaq[j1]
            Gamma221d1[i,1]=multiply(0.5,(Gamma221[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1] - Gamma221[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1])) / deltaq[j1]
            Gamma222d1[i,1]=multiply(0.5,(Gamma222[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1] - Gamma222[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1])) / deltaq[j1]
        else:
            if 2 == firstdevneighbours[i,dot(4,(j1 - 1)) + 1]:
                Gamma111d1[i,1]=(dot(- 1.5,Gamma111[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1]) + dot(2,Gamma111[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1]) - dot(0.5,Gamma111[firstdevneighbours[i,dot(4,(j1 - 1)) + 4],1])) / deltaq[j1]
                Gamma112d1[i,1]=(dot(- 1.5,Gamma112[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1]) + dot(2,Gamma112[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1]) - dot(0.5,Gamma112[firstdevneighbours[i,dot(4,(j1 - 1)) + 4],1])) / deltaq[j1]
                Gamma121d1[i,1]=(dot(- 1.5,Gamma121[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1]) + dot(2,Gamma121[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1]) - dot(0.5,Gamma121[firstdevneighbours[i,dot(4,(j1 - 1)) + 4],1])) / deltaq[j1]
                Gamma122d1[i,1]=(dot(- 1.5,Gamma122[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1]) + dot(2,Gamma122[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1]) - dot(0.5,Gamma122[firstdevneighbours[i,dot(4,(j1 - 1)) + 4],1])) / deltaq[j1]
                Gamma211d1[i,1]=(dot(- 1.5,Gamma211[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1]) + dot(2,Gamma211[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1]) - dot(0.5,Gamma211[firstdevneighbours[i,dot(4,(j1 - 1)) + 4],1])) / deltaq[j1]
                Gamma212d1[i,1]=(dot(- 1.5,Gamma212[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1]) + dot(2,Gamma212[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1]) - dot(0.5,Gamma212[firstdevneighbours[i,dot(4,(j1 - 1)) + 4],1])) / deltaq[j1]
                Gamma221d1[i,1]=(dot(- 1.5,Gamma221[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1]) + dot(2,Gamma221[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1]) - dot(0.5,Gamma221[firstdevneighbours[i,dot(4,(j1 - 1)) + 4],1])) / deltaq[j1]
                Gamma222d1[i,1]=(dot(- 1.5,Gamma222[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1]) + dot(2,Gamma222[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1]) - dot(0.5,Gamma222[firstdevneighbours[i,dot(4,(j1 - 1)) + 4],1])) / deltaq[j1]
            else:
                if 3 == firstdevneighbours[i,dot(4,(j1 - 1)) + 1]:
                    Gamma111d1[i,1]=(dot(1.5,Gamma111[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1]) - dot(2,Gamma111[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1]) + dot(0.5,Gamma111[firstdevneighbours[i,dot(4,(j1 - 1)) + 4],1])) / deltaq[j1]
                    Gamma112d1[i,1]=(dot(1.5,Gamma112[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1]) - dot(2,Gamma112[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1]) + dot(0.5,Gamma112[firstdevneighbours[i,dot(4,(j1 - 1)) + 4],1])) / deltaq[j1]
                    Gamma121d1[i,1]=(dot(1.5,Gamma121[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1]) - dot(2,Gamma121[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1]) + dot(0.5,Gamma121[firstdevneighbours[i,dot(4,(j1 - 1)) + 4],1])) / deltaq[j1]
                    Gamma122d1[i,1]=(dot(1.5,Gamma122[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1]) - dot(2,Gamma122[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1]) + dot(0.5,Gamma122[firstdevneighbours[i,dot(4,(j1 - 1)) + 4],1])) / deltaq[j1]
                    Gamma211d1[i,1]=(dot(1.5,Gamma211[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1]) - dot(2,Gamma211[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1]) + dot(0.5,Gamma211[firstdevneighbours[i,dot(4,(j1 - 1)) + 4],1])) / deltaq[j1]
                    Gamma212d1[i,1]=(dot(1.5,Gamma212[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1]) - dot(2,Gamma212[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1]) + dot(0.5,Gamma212[firstdevneighbours[i,dot(4,(j1 - 1)) + 4],1])) / deltaq[j1]
                    Gamma221d1[i,1]=(dot(1.5,Gamma221[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1]) - dot(2,Gamma221[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1]) + dot(0.5,Gamma221[firstdevneighbours[i,dot(4,(j1 - 1)) + 4],1])) / deltaq[j1]
                    Gamma222d1[i,1]=(dot(1.5,Gamma222[firstdevneighbours[i,dot(4,(j1 - 1)) + 2],1]) - dot(2,Gamma222[firstdevneighbours[i,dot(4,(j1 - 1)) + 3],1]) + dot(0.5,Gamma222[firstdevneighbours[i,dot(4,(j1 - 1)) + 4],1])) / deltaq[j1]
        j2=2
        if 1 == firstdevneighbours[i,dot(4,(j2 - 1)) + 1]:
            Gamma111d2[i,1]=multiply(0.5,(Gamma111[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1] - Gamma111[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1])) / deltaq[j2]
            Gamma112d2[i,1]=multiply(0.5,(Gamma112[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1] - Gamma112[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1])) / deltaq[j2]
            Gamma121d2[i,1]=multiply(0.5,(Gamma121[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1] - Gamma121[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1])) / deltaq[j2]
            Gamma122d2[i,1]=multiply(0.5,(Gamma122[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1] - Gamma122[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1])) / deltaq[j2]
            Gamma211d2[i,1]=multiply(0.5,(Gamma211[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1] - Gamma211[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1])) / deltaq[j2]
            Gamma212d2[i,1]=multiply(0.5,(Gamma212[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1] - Gamma212[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1])) / deltaq[j2]
            Gamma221d2[i,1]=multiply(0.5,(Gamma221[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1] - Gamma221[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1])) / deltaq[j2]
            Gamma222d2[i,1]=multiply(0.5,(Gamma222[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1] - Gamma222[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1])) / deltaq[j2]
        else:
            if 2 == firstdevneighbours[i,dot(4,(j2 - 1)) + 1]:
                Gamma111d2[i,1]=(dot(- 1.5,Gamma111[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1]) + dot(2,Gamma111[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1]) - dot(0.5,Gamma111[firstdevneighbours[i,dot(4,(j2 - 1)) + 4],1])) / deltaq[j2]
                Gamma112d2[i,1]=(dot(- 1.5,Gamma112[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1]) + dot(2,Gamma112[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1]) - dot(0.5,Gamma112[firstdevneighbours[i,dot(4,(j2 - 1)) + 4],1])) / deltaq[j2]
                Gamma121d2[i,1]=(dot(- 1.5,Gamma121[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1]) + dot(2,Gamma121[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1]) - dot(0.5,Gamma121[firstdevneighbours[i,dot(4,(j2 - 1)) + 4],1])) / deltaq[j2]
                Gamma122d2[i,1]=(dot(- 1.5,Gamma122[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1]) + dot(2,Gamma122[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1]) - dot(0.5,Gamma122[firstdevneighbours[i,dot(4,(j2 - 1)) + 4],1])) / deltaq[j2]
                Gamma211d2[i,1]=(dot(- 1.5,Gamma211[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1]) + dot(2,Gamma211[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1]) - dot(0.5,Gamma211[firstdevneighbours[i,dot(4,(j2 - 1)) + 4],1])) / deltaq[j2]
                Gamma212d2[i,1]=(dot(- 1.5,Gamma212[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1]) + dot(2,Gamma212[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1]) - dot(0.5,Gamma212[firstdevneighbours[i,dot(4,(j2 - 1)) + 4],1])) / deltaq[j2]
                Gamma221d2[i,1]=(dot(- 1.5,Gamma221[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1]) + dot(2,Gamma221[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1]) - dot(0.5,Gamma221[firstdevneighbours[i,dot(4,(j2 - 1)) + 4],1])) / deltaq[j2]
                Gamma222d2[i,1]=(dot(- 1.5,Gamma222[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1]) + dot(2,Gamma222[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1]) - dot(0.5,Gamma222[firstdevneighbours[i,dot(4,(j2 - 1)) + 4],1])) / deltaq[j2]
            else:
                if 3 == firstdevneighbours[i,dot(4,(j2 - 1)) + 1]:
                    Gamma111d2[i,1]=(dot(1.5,Gamma111[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1]) - dot(2,Gamma111[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1]) + dot(0.5,Gamma111[firstdevneighbours[i,dot(4,(j2 - 1)) + 4],1])) / deltaq[j2]
                    Gamma112d2[i,1]=(dot(1.5,Gamma112[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1]) - dot(2,Gamma112[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1]) + dot(0.5,Gamma112[firstdevneighbours[i,dot(4,(j2 - 1)) + 4],1])) / deltaq[j2]
                    Gamma121d2[i,1]=(dot(1.5,Gamma121[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1]) - dot(2,Gamma121[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1]) + dot(0.5,Gamma121[firstdevneighbours[i,dot(4,(j2 - 1)) + 4],1])) / deltaq[j2]
                    Gamma122d2[i,1]=(dot(1.5,Gamma122[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1]) - dot(2,Gamma122[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1]) + dot(0.5,Gamma122[firstdevneighbours[i,dot(4,(j2 - 1)) + 4],1])) / deltaq[j2]
                    Gamma211d2[i,1]=(dot(1.5,Gamma211[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1]) - dot(2,Gamma211[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1]) + dot(0.5,Gamma211[firstdevneighbours[i,dot(4,(j2 - 1)) + 4],1])) / deltaq[j2]
                    Gamma212d2[i,1]=(dot(1.5,Gamma212[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1]) - dot(2,Gamma212[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1]) + dot(0.5,Gamma212[firstdevneighbours[i,dot(4,(j2 - 1)) + 4],1])) / deltaq[j2]
                    Gamma221d2[i,1]=(dot(1.5,Gamma221[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1]) - dot(2,Gamma221[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1]) + dot(0.5,Gamma221[firstdevneighbours[i,dot(4,(j2 - 1)) + 4],1])) / deltaq[j2]
                    Gamma222d2[i,1]=(dot(1.5,Gamma222[firstdevneighbours[i,dot(4,(j2 - 1)) + 2],1]) - dot(2,Gamma222[firstdevneighbours[i,dot(4,(j2 - 1)) + 3],1]) + dot(0.5,Gamma222[firstdevneighbours[i,dot(4,(j2 - 1)) + 4],1])) / deltaq[j2]
    
    # Rlijk = Gamma_lik/j - Gamma_lij/k + Gamma_ljs*Gamma_sik - Gamma_lks*Gamma_sij
    
    R1111=Gamma111d1 - Gamma111d1 + (multiply(Gamma111,Gamma111) + multiply(Gamma112,Gamma211)) - (multiply(Gamma111,Gamma111) + multiply(Gamma112,Gamma211))
    R1112=Gamma112d1 - Gamma111d2 + (multiply(Gamma111,Gamma112) + multiply(Gamma112,Gamma212)) - (multiply(Gamma121,Gamma111) + multiply(Gamma122,Gamma211))
    R1121=Gamma111d2 - Gamma112d1 + (multiply(Gamma121,Gamma111) + multiply(Gamma122,Gamma211)) - (multiply(Gamma111,Gamma112) + multiply(Gamma112,Gamma212))
    R1122=Gamma112d2 - Gamma112d2 + (multiply(Gamma121,Gamma112) + multiply(Gamma122,Gamma212)) - (multiply(Gamma121,Gamma112) + multiply(Gamma122,Gamma212))
    R1211=Gamma121d1 - Gamma121d1 + (multiply(Gamma111,Gamma121) + multiply(Gamma112,Gamma221)) - (multiply(Gamma111,Gamma121) + multiply(Gamma112,Gamma221))
    R1212=Gamma122d1 - Gamma121d2 + (multiply(Gamma111,Gamma122) + multiply(Gamma112,Gamma222)) - (multiply(Gamma121,Gamma121) + multiply(Gamma122,Gamma221))
    R1221=Gamma121d2 - Gamma122d1 + (multiply(Gamma121,Gamma121) + multiply(Gamma122,Gamma221)) - (multiply(Gamma111,Gamma122) + multiply(Gamma112,Gamma222))
    R1222=Gamma122d2 - Gamma122d2 + (multiply(Gamma121,Gamma122) + multiply(Gamma122,Gamma222)) - (multiply(Gamma121,Gamma122) + multiply(Gamma122,Gamma222))
    R2111=Gamma211d1 - Gamma211d1 + (multiply(Gamma211,Gamma111) + multiply(Gamma212,Gamma211)) - (multiply(Gamma211,Gamma111) + multiply(Gamma212,Gamma211))
    R2112=Gamma212d1 - Gamma211d2 + (multiply(Gamma211,Gamma112) + multiply(Gamma212,Gamma212)) - (multiply(Gamma221,Gamma111) + multiply(Gamma222,Gamma211))
    R2121=Gamma211d2 - Gamma212d1 + (multiply(Gamma221,Gamma111) + multiply(Gamma222,Gamma211)) - (multiply(Gamma211,Gamma112) + multiply(Gamma212,Gamma212))
    R2122=Gamma212d2 - Gamma212d2 + (multiply(Gamma221,Gamma112) + multiply(Gamma222,Gamma212)) - (multiply(Gamma221,Gamma112) + multiply(Gamma222,Gamma212))
    R2211=Gamma221d1 - Gamma221d1 + (multiply(Gamma211,Gamma121) + multiply(Gamma212,Gamma221)) - (multiply(Gamma211,Gamma121) + multiply(Gamma212,Gamma221))
    R2212=Gamma222d1 - Gamma221d2 + (multiply(Gamma211,Gamma122) + multiply(Gamma212,Gamma222)) - (multiply(Gamma221,Gamma121) + multiply(Gamma222,Gamma221))
    R2221=Gamma221d2 - Gamma222d1 + (multiply(Gamma221,Gamma121) + multiply(Gamma222,Gamma221)) - (multiply(Gamma211,Gamma122) + multiply(Gamma212,Gamma222))
    R2222=Gamma222d2 - Gamma222d2 + (multiply(Gamma221,Gamma122) + multiply(Gamma222,Gamma222)) - (multiply(Gamma221,Gamma122) + multiply(Gamma222,Gamma222))
    # Riemanntensor_lijk = g_ls*R_sijk
    Riemanntensor1111=multiply(g11,R1111) + multiply(g12,R2111)
    Riemanntensor1112=multiply(g11,R1112) + multiply(g12,R2112)
    Riemanntensor1121=multiply(g11,R1121) + multiply(g12,R2121)
    Riemanntensor1122=multiply(g11,R1122) + multiply(g12,R2122)
    Riemanntensor1211=multiply(g11,R1211) + multiply(g12,R2211)
    Riemanntensor1212=multiply(g11,R1212) + multiply(g12,R2212)
    Riemanntensor1221=multiply(g11,R1221) + multiply(g12,R2221)
    Riemanntensor1222=multiply(g11,R1222) + multiply(g12,R2222)
    Riemanntensor2111=multiply(g21,R1111) + multiply(g22,R2111)
    Riemanntensor2112=multiply(g21,R1112) + multiply(g22,R2112)
    Riemanntensor2121=multiply(g21,R1121) + multiply(g22,R2121)
    Riemanntensor2122=multiply(g21,R1122) + multiply(g22,R2122)
    Riemanntensor2211=multiply(g21,R1211) + multiply(g22,R2211)
    Riemanntensor2212=multiply(g21,R1212) + multiply(g22,R2212)
    Riemanntensor2221=multiply(g21,R1221) + multiply(g22,R2221)
    Riemanntensor2222=multiply(g21,R1222) + multiply(g22,R2222)
    Riemanntensor=matlabarray(cat(Riemanntensor1111,Riemanntensor1112,Riemanntensor1121,Riemanntensor1122,Riemanntensor1211,Riemanntensor1212,Riemanntensor1221,Riemanntensor1222,Riemanntensor2111,Riemanntensor2112,Riemanntensor2121,Riemanntensor2122,Riemanntensor2211,Riemanntensor2212,Riemanntensor2221,Riemanntensor2222))
    return Riemanntensor