# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def computereciprocalmetriccoefficients2D(contravariantbase=None,*args,**kwargs):
    varargin = computereciprocalmetriccoefficients2D.varargin
    nargin = computereciprocalmetriccoefficients2D.nargin

    ##
#        Project: Fluid - structure interaction on deformable surfaces
#         Author: Luca Di Stasio
#    Institution: ETH Zrich
#                 Institute for Building Materials
# Research group: Computational Physics for Engineering Materials
#        Version: 0.1
#  Creation date: July 18th, 2014
#    Last update: July 18th, 2014
    
    #    Description: 
#          Input: 
#         Output:
    
    ##
    
    g11=sum(multiply(contravariantbase[:,1:2],contravariantbase[:,1:2]),2)
    g22=sum(multiply(contravariantbase[:,3:4],contravariantbase[:,3:4]),2)
    g12=sum(multiply(contravariantbase[:,1:2],contravariantbase[:,3:4]),2)
    g=multiply(g11,g22) - multiply(g12,g12)
    sqrtg=sqrt(g)
    reciprocalmetriccoefficients=matlabarray(cat(g11,g22,g12))
    return reciprocalmetriccoefficients,g,sqrtg