# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def computecovariantbase2D(N=None,deltaq=None,lattice=None,firstdevneighbours=None,*args,**kwargs):
    varargin = computecovariantbase2D.varargin
    nargin = computecovariantbase2D.nargin

    ##
#        Project: Fluid - structure interaction on deformable surfaces
#         Author: Luca Di Stasio
#    Institution: ETH Zrich
#                 Institute for Building Materials
# Research group: Computational Physics for Engineering Materials
#        Version: 0.1
#  Creation date: July 11th, 2014
#    Last update: July 11th, 2014
    
    #    Description: 
#          Input: 
#         Output:
    
    ##
    
    covariantbase=zeros(N,4)
    for i in arange(1,N).reshape(-1):
        for j in arange(1,2).reshape(-1):
            if 1 == firstdevneighbours[i,dot(4,(j - 1)) + 1]:
                covariantbase[i,dot(2,(j - 1)) + 1:dot(2,(j - 1)) + 2]=multiply(0.5,cat((lattice[firstdevneighbours[i,dot(4,(j - 1)) + 3],5] - lattice[firstdevneighbours[i,dot(4,(j - 1)) + 2],5]),(lattice[firstdevneighbours[i,dot(4,(j - 1)) + 3],6] - lattice[firstdevneighbours[i,dot(4,(j - 1)) + 2],6]))) / deltaq[j]
            else:
                if 2 == firstdevneighbours[i,dot(4,(j - 1)) + 1]:
                    covariantbase[i,dot(2,(j - 1)) + 1:dot(2,(j - 1)) + 2]=cat((dot(- 1.5,lattice[firstdevneighbours[i,dot(4,(j - 1)) + 2],5]) + dot(2,lattice[firstdevneighbours[i,dot(4,(j - 1)) + 3],5]) - dot(0.5,lattice[firstdevneighbours[i,dot(4,(j - 1)) + 4],5])),(dot(- 1.5,lattice[firstdevneighbours[i,dot(4,(j - 1)) + 2],6]) + dot(2,lattice[firstdevneighbours[i,dot(4,(j - 1)) + 3],6]) - dot(0.5,lattice[firstdevneighbours[i,dot(4,(j - 1)) + 4],6]))) / deltaq[j]
                else:
                    if 3 == firstdevneighbours[i,dot(4,(j - 1)) + 1]:
                        covariantbase[i,dot(2,(j - 1)) + 1:dot(2,(j - 1)) + 2]=cat((dot(1.5,lattice[firstdevneighbours[i,dot(4,(j - 1)) + 2],5]) - dot(2,lattice[firstdevneighbours[i,dot(4,(j - 1)) + 3],5]) + dot(0.5,lattice[firstdevneighbours[i,dot(4,(j - 1)) + 4],5])),(dot(- 1.5,lattice[firstdevneighbours[i,dot(4,(j - 1)) + 2],6]) + dot(2,lattice[firstdevneighbours[i,dot(4,(j - 1)) + 3],6]) - dot(0.5,lattice[firstdevneighbours[i,dot(4,(j - 1)) + 4],6]))) / deltaq[j]
    